### PR TITLE
Use kata-deploy to install and configure kata

### PR DESCRIPTION
**Pull request by krsna1729**
Resolves: #38 

TODO:
Fix FC failing

```
NAME                                   READY   STATUS              RESTARTS   AGE
php-apache-kata-fc-6c6f484c4b-s5rz7    0/1     ContainerCreating   0          4m45s
php-apache-kata-qemu-bc4c55994-4vh4b   1/1     Running             0          4m45s
php-apache-runc-7cc9dcb54f-4sv2c       1/1     Running             0          4m45s
test-cpumanager-kata                   0/1     Completed           0          4m45s
test-cpumanager-runc                   0/1     Completed           0          4m45s
```
```
  Warning  FailedCreatePodSandBox  8s (x5 over 82s)  kubelet, clr-01    Failed create pod sandbox: rpc error: code = Unknown desc = container create failed: Failed to check if grpc server is working: context deadline exceeded
```

Signed-off-by: Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>

### CODE REVIEW

**Comment by krsna1729** [comment]
The issue is with vsock and not this patch. qemu also fails when told to `use_vsock`. removing DNM label.

@mcastelino PTAL and merge

**Comment by ganeshmaharaj** [comment]
@mcastelino, are there any clear specific stuff for kata-fc that might hinder things working if we use the ones shipped with kata-deploy?

**Comment by mcastelino** [comment]
> @mcastelino, are there any clear specific stuff for kata-fc that might hinder things working if we use the ones shipped with kata-deploy?

The benefit of using the firecracker that comes with clear is that it will updated as clear updates with any security and other fixes. The same reason for using containerd packaged with clear.

But then we will split across deployment methodologies.

@egernst @krsna1729 what is our update model for kata-deploy?

**Comment by egernst** [comment]
> what is our update model for kata-deploy?
@mcastelino - we update the binaries on a per release basis (scheduled every 2 weeks, though quicker if issues are identified)

**Comment by krsna1729** [comment]
@mcastelino @ganeshmaharaj @egernst @grahamwhaley @bryteise 
Time to think about how the infra is supposed to be upgraded from node and this stack perspective

**Comment by mythi** [comment]
@krsna1729 kubeadm has documentation how to use ```kubeadm upgrade``` to update the cluster and we have a tutorial how to take that in Clear/swupd world.

Back in when we changed 1.12->1.13 I used the tutorial to test it's possible to update a cluster running this stack. I did not look kata specific things then tough.

**Comment by krsna1729** [comment]
Created #53 to capture

**Comment by ganeshmaharaj** [comment]
Tested this patch and +1 after two things happen.

https://github.com/clearlinux/cloud-native-setup/pull/59 <-- that fixes the issue where kata-runtime definition in crio.conf by clear does not get overwritten.
https://github.com/kata-containers/packaging/pull/334 <-- So that network_ns_lifecycle string is not duplicated and breaks crio service.

**Comment by krsna1729** [comment]
@ganeshmaharaj we should move this block to `setup_system.sh` in this patch if we want to use kata-deploy right?

```
sudo mkdir -p /etc/crio/
if [ ! -f /etc/crio/crio.conf ]; then
  sudo cp /usr/share/defaults/crio/crio.conf /etc/crio/crio.conf
fi
```

**Comment by ganeshmaharaj** [comment]
@krsna1729 we can do the move as part of a clean-up patch where we will also flush the vagrant file. for now, this should be alright to have. if there are no objections, we can merge this.

**Comment by krsna1729** [comment]
@mcastelino?
cc @AntonioMeireles for insights

**Comment by AntonioMeireles** [comment]
@sai

 fwiw i find somewhat ironic the use of kata-deploy to install kata given
that imho the current cloud-native-setup structural design flaw is the
insistence to use the in-distro kubelet/kubeadm/kubectl which basically
just breaks updating at will . in other words kata-deploy is much needed
progress in right direction until swupd featureset improved in this very
specific regard 😃

**Comment by mythi** [comment]
> insistence to use the in-distro kubelet/kubeadm/kubectl which basically just breaks updating at will

I've successfully updated a cluster with the swupd model when the k8s minor version changes (i.e., API compatibility breaks) and it works. cloud-native-setup does not mandate to use in-distro k8s binaries as far as I can tell (you just need to have them installed). What problems do you see with updates today (other than the lack of version pinning which isn't cloud-native bundle specific)?

**Comment by krsna1729** [comment]
needs rebase

**Comment by krsna1729** [comment]
rebased and verified working with upstream kata-deploy latest image

**Pull request merged**
