### PR TITLE
Kustomize kubeadm.yaml config file

### PR DESCRIPTION
**Pull request by juliocri**
This change splits current configuration sections of kubeadm.yaml in single files in order to make it easier customizations using kustomize. create_stack script now build a new on the fly kubeadm.yaml file just before to execute kubeadm init.

### CODE REVIEW

**Comment by jascott1** [comment]
Why don't we use Kustomize's patches instead of `sed`?

**Comment by juliocri** [comment]
> Why don't we use Kustomize's patches instead of `sed`? I guess the env vars require it but we should consider patches for the other modifications.

Hey @jascott1 I think env vars can enter to the game of using patches without sed,  I submitted a commit with a proposal of implementation of patches using patchesJson6902 using yaml files as input.

**Comment by mythi** [comment]
AFAICS, splitting `kubeadm.yaml` to three isn't necessary. I'd also suggest to use json style one-line patches that are all echoed in one patches .yaml.

**Comment by jascott1** [comment]
I think we should just make a static kubeadm, keep the seds for env vars and use patches. Heredoc' ing everything is not a desirable way to generate yaml imo.

**Comment by juliocri** [comment]
> I think we should just make a static kubeadm, keep the seds for env vars and use patches. Heredoc' ing everything is not a desirable way to generate yaml imo.

yeah, agree! I think this change is getting cleaner, `sed` are keep for env vars which injects its value, and patches for those other vars that are adding extra config such is the case of `$HIGH_POD_COUNT`

**Comment by obedmr** [comment]
@juliocri, it seem like you will need to fix the conflicting files.

**Comment by juliocri** [comment]
> @juliocri, it seem like you will need to fix the conflicting files.

Hey @obedmr Thanks for the follow up, what do you think is missing? maybe a commit squash? @jascott1

**Comment by juliocri** [comment]
> yes, please squash

For sure! now this PR is squashed in a single commit.

**Comment by juliocri** [comment]
@jascott1 ^_^

**Comment by obedmr** [comment]
@jascott1 any comment on this? Is it ok for merge? it's blocking new requires changes for scaling efforts.

**Comment by jascott1** [comment]
@obedmr review in progress :)

**Pull request merged**
