### PR TITLE
[WIP][DNM]machine-check: Use node problem detector to detect machine check

### PR DESCRIPTION
**Pull request by mcastelino**
Use node problem detector to detect machine check errors reported
in a cluster. When a machine check happens in a cluster it will
generate a event and report it to kubernetes

```
clear@clr-01 ~/clr-k8s-examples $ kubectl get events
LAST SEEN   TYPE      REASON             OBJECT
MESSAGE
11m         Warning   Hardware Error     node/clr-01
mce: [Hardware Error]: Machine check events logged
11m         Warning   Hardware Error     node/clr-01
Hardware event. This is not a software error.

```

Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>

### CODE REVIEW

**Comment by ahsan518** [comment]
Reviewing changes and testing

**Comment by krsna1729** [comment]
#34

**Comment by ahsan518** [comment]
Tested this patch and works as expected. Shall we merge this and add the Feature 34 later in a different pull request @krsna1729

**Comment by krsna1729** [comment]
@ahsan518 i was cross-referencing to the initial issue opened to look at node problem detector. dont mind me.

**Comment by jascott1** [comment]
Closing this as it is superseded by #160

**Pull request closed without merging**
