### PR TITLE
Add license for admit-kata

### LINKED ISSUE #4: Add licence files from upstream repos

### PR DESCRIPTION
**Pull request by jascott1**
Closes #4

Signed-off-by: Justin Scott <justin.a.scott@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
#4 talks about adding the licenses from upstream projects - did admit-kata take code from upstream? If not, notionally it would already be covered by apache2 as that is the licence file in the parent root dir of the tree.... having said that:

- if this is code not taken from elsewhere, adding the file is fine and not a problem anyway :-)
- if the code was taken (even partially) from elsewhere, can we add a reference to that in the README as well maybe.

but, generally, lgtm.

**Comment by krsna1729** [comment]
@grahamwhaley I think the existing pointers are good enough for admit-kata? @jascott1 @ganeshmaharaj i dont think we need this PR?

https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/admit-kata/deploy/webhook-registration.yaml.tpl#L1-L3
https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/admit-kata/deploy/webhook.yaml#L1-L3


https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/admit-kata/versions

**Comment by jascott1** [comment]
I will defer to @grahamwhaley but have no problem closing this.

**Comment by grahamwhaley** [comment]
never planning on shipping it standalone, outside of this repo, then you can probably close it.
Over in Kata we go belt and braces - we do have a top level license file, but every source file and any file that can carry a copyright head has an SPDX style (short style) licencse header in it as well..
So, I think either you:
- have one license file at the top level, no specific licences in *your* files
- or you have license headers in all your files.

I think this tree does more like the former.
And, of course, still pull down the license files for anything you are copying in (nice move...)

**Comment by jascott1** [comment]
Thanks! I will close the PR and the issue.

**Pull request closed without merging**
