### PR TITLE
metrics: improve documentation

### PR DESCRIPTION
**Pull request by grahamwhaley**
Improve the documentation for the metrics subsystem.
 - Improve the top level README
 - move the scaling details into the scaling subdir, rewrite and embellish.

### CODE REVIEW

**Comment by GabyCT** [comment]
thank you @grahamwhaley

**Comment by amshinde** [comment]
ack @grahamwhaley, thanks for taking this up.

**Comment by grahamwhaley** [comment]
@dklyle - don't suppose you could check and ack this could you? Needs somebody to ack to merge.

**Pull request merged**
