### PR TITLE
Remove applying runtimeclass CRD

### PR DESCRIPTION
**Pull request by krsna1729**
CRD was removed as part of 1.14 update. Missed update to create_stack

Fixes: #84

Signed-off-by: Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>

### CODE REVIEW

**Comment by mcastelino** [comment]
@krsna1729 @ganeshmaharaj we should update our readme to say our scripts will only work on 1.14 and beyond.

So as long as the user uses the files from the bundle vs here they should be fine.

@ganeshmaharaj did you all ensure the scripts got updated in the clearlinux cloud-native-basic example scripts. We package the scripts today as part of CL

/cc @bryteise

**Comment by krsna1729** [comment]
@mcastelino @bryteise  yes we need this updated in the bundle

**Comment by ganeshmaharaj** [comment]
+1. Manohar we should cut a release now and i can update the scripts in clear. Anything we would like to add before i cut the release?

**Comment by mcastelino** [comment]
@ganeshmaharaj @bryteise yes we need to cut a new release of the cloud-native-basic bundle with the updated scripts. Otherwise the scripts will not work with the version of kubernetes tools and kubelet packaged. We need to do this each time we rev any of the cloud-native-basic components.

**Comment by ganeshmaharaj** [comment]
fair enough. We don't have a auto-trigger of sorts to do this today. Needs a human tracking it. We need to figure out how to automate this.

**Pull request merged**
