### PR TITLE
Updating the deprecated beta workload APIs for K8s v1.16

### LINKED ISSUE #220: Stop referencing deprecated beta workload APIs
Kubernetes 1.16 ended support for v1beta1 and v1beta2 API. These references need to be updated in all files

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals

The following APIs are no longer served by default:

All resources under apps/v1beta1 and apps/v1beta2 - use apps/v1 instead
daemonsets, deployments, replicasets resources under extensions/v1beta1 - use apps/v1 instead
networkpolicies resources under extensions/v1beta1 - use networking.k8s.io/v1 instead
podsecuritypolicies resources under extensions/v1beta1 - use policy/v1beta1 instead

./clr-k8s-examples/admit-kata/deploy/webhook-registration.yaml.tpl(5): apiVersion: admissionregistration.k8s.io/v1beta1
./clr-k8s-examples/7-rook/overlays/v0.8.3/patch_operator.yaml(2): apiVersion: apps/v1beta1
./clr-k8s-examples/admit-kata/deploy/webhook.yaml(5): apiVersion: extensions/v1beta1
./clr-k8s-examples/tests/deploy-svc-ing/test-ingress-kata.yaml(1): apiVersion: extensions/v1beta1
./clr-k8s-examples/tests/deploy-svc-ing/test-ingress-runc.yaml(1): apiVersion: extensions/v1beta1

### PR DESCRIPTION
**Pull request by knangia**
Fixes #220 
Signed-off-by: Khanak Nangia khanak.nangia@intel.com

### CODE REVIEW

**Comment by knangia** [comment]
Tested with k8s v1.16.2, crio, latest cloud-native repo, and create_stack.sh all.
All pods are up and running, and Sonobuoy test suite passed

**Comment by ahsan518** [comment]
What about the ones in kubeadm.yaml file ?

**Comment by knangia** [comment]
not all APIs are deprecated, kubelet config and cluster config APIs are not updated for K8s v1.16.
Reference : https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals

**Comment by ahsan518** [comment]
👍

**Comment by ahsan518** [comment]
Tested, works as expected.

**Pull request merged**
