### PR TITLE
setup_system: add proxy configuration for docker

### PR DESCRIPTION
**Pull request by askervin**
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>

### CODE REVIEW

**Comment by krsna1729** [comment]
Was $RUNNER with docker tried? Also we don't install docker as part of this setup. Can you describe more in the commit and the first message in this conversation?

https://github.com/clearlinux/cloud-native-setup/blob/be164144e4c69c12cd2b2b4e835ec3cd21010839/clr-k8s-examples/setup_system.sh#L115-L124

**Comment by askervin** [comment]
I'm running `metrics` scripts in a setup where clear-live-server has been just installed and `setup_system.sh` executed.

Running `cloud-native-setup/metrics/report/makereport.sh` needs docker. Launching `dockerd` will not be enough: successful run of `makereport.sh` needs docker client proxy configuration (or alternatively extra proxy handling software).

The point of this patch is to extend `setup_system.sh` so that `grabdata.sh` and `makereport.sh` run without any further setups or manual proxy configurations.

**Comment by krsna1729** [comment]
move it into metrics. does not make sense to do it on every machine in the cluster.

**Comment by askervin** [comment]
Thanks! Closing.

**Pull request closed without merging**
