### PR TITLE
runtimeClass updates for kubernetes 1.14

### PR DESCRIPTION
**Pull request by egernst**
RuntimeClass moved from alpha to beta. Remove the feature gates, remove
the runtimeClass CRD since it is a built in type, and take the new data
structure into account.

Signed-off-by: Eric Ernst <eric.ernst@intel.com>

### CODE REVIEW

**Comment by krsna1729** [comment]
@hnanni please take a look at this PR. Test with in-house clear versions.
Resolves: #77

**Comment by krsna1729** [comment]
Waiting on clear

**Comment by mythi** [comment]
> Waiting on clear

Is this being worked on?

**Comment by krsna1729** [comment]
@mythi we are waiting on clear push out 1.14. Once there we can test and merge these 1.14 specific PR.

**Comment by ganeshmaharaj** [comment]
Working on it. Will have clear updated to 1.14 for k8s soon.

**Comment by hnanni** [comment]
Thanks, `kubeadm init --config=./kubeadm.yaml ` completed:
`Your Kubernetes control-plane has initialized successfully!`

I'm holding the push of 1.14 to the CLR repository until the internal test of k8s (based on cloud-native-setup scripts) is ready. After the fix this PR provides, the current issue/error is that `kubeadm join` is failing ( #83 )

**Comment by ganeshmaharaj** [comment]
@hnanni how goes the update of clear to 1.14 packages for k8s? I have a cri-o updates to match k8s, but holding off until we get the k8s version in.

**Comment by hnanni** [comment]
@ganeshmaharaj  Find k8s 1.14 in the just released CLR 28630 version. I've tested it with https://github.com/clearlinux/cloud-native-setup/pull/80.

**Comment by ganeshmaharaj** [comment]
@hnanni That's awesome. can we merge this patch then? I will upstream the cri-o update today.

**Comment by hnanni** [comment]
yes, please merge #80

**Pull request merged**
